name: publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2

            - run: deno fmt --check
            - run: npx jsr publish
